export const ui = {
  nav: {
    me: "Me",
    projects: "Projects",
    experience: "Experience",
    contact: "Contact",
    settings: "Settings",
  },
  settings: {
    track: "track",
    noTracks: "— No tracks —",
  },
  status: {
    musicKey: "[M] — Music",
    weatherKey: "[W] — Weather",
    musicOn: "on",
    musicOff: "off",
  },
  side: {
    music: "MUSIC",
    style: "STYLE",
    weather: "WEATHER",
    portfolio: "PORTFOLIO",
  },
  themes: {
    green: "GREEN",
    amber: "AMBER",
    white: "WHITE",
    dim: "DIM",
  },
  weather: {
    off: "NONE",
    rain: "RAIN",
    autumn: "AUTUMN",
    winter: "WINTER",
  },
  me: {
    downloadCv: "Download CV",
    labels: {
      name: "Name",
      role: "Role",
    },
  },
  projects: {
    url: "URL",
  },
  experience: {
    period: "Date",
    role: "Role",
  },
  editor: {
    title: "EDIT PORTFOLIO",
    hint: "Changes are saved in this browser only. Use Export to download portfolio.json.",
    open: "Edit",
    save: "Save",
    export: "Export",
    reset: "Reset",
    cancel: "Cancel",
    close: "Close",
    sections: {
      profile: "Profile",
      skills: "Skills",
      projects: "Projects",
      experience: "Experience",
      contact: "Contact",
    },
    fields: {
      photo: "Photo",
      skillCategory: "Category",
      skillName: "Skill",
      projectTitle: "Title",
      projectUrl: "URL",
      projectDescription: "Description",
      company: "Company",
      period: "Date",
      role: "Role",
      description: "Description",
      contactLabel: "Label",
      contactValue: "Value",
      contactHref: "Link",
    },
    addProject: "Add project",
    addExperience: "Add experience",
    addContact: "Add contact",
    addSkillGroup: "Add category",
    addSkill: "Add skill",
    remove: "Remove",
    removeCategory: "Remove category",
    errors: {
      nameRequired: "Name is required.",
      roleRequired: "Role is required.",
      photoRequired: "Photo link is required.",
      skillCategoryRequired: "Each skill category needs a name.",
      projectTitleRequired: "Each project needs a title.",
      projectUrlRequired: "Each project needs a URL.",
      experienceCompanyRequired: "Each experience entry needs a company.",
      contactLabelRequired: "Each contact entry needs a label.",
      contactValueRequired: "Each contact entry needs a value.",
      contactHrefRequired: "Each contact entry needs a link.",
    },
  },
} as const;
